// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kodia-studio/kodia/internal/core/domain"
)

type Mutation struct {
}

type PaginatedUsers struct {
	Users   []*domain.User `json:"users"`
	Total   int            `json:"total"`
	Page    int            `json:"page"`
	PerPage int            `json:"perPage"`
}

type Query struct {
}

type UpdateUserInput struct {
	Name      *string `json:"name,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}
