package docs

// SwaggerInfo contains exported Swagger definitions.
// This file is auto-generated by swag command, but you need to define the main swagger info here.

// @title Kodia API
// @version 1.0.0
// @description Professional REST API built with Go/Gin and Kodia Framework
// @termsOfService http://swagger.io/terms/

// @contact.name Kodia API Support
// @contact.url https://kodia.dev
// @contact.email support@kodia.dev

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @basePath /api
// @schemes http https

// @securityDefinitions.apiKey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// @x-logo
// @url https://kodia.dev/logo.png
// @altText Kodia Framework
