package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"

	"github.com/kodia-studio/kodia/graph/model"
	"github.com/kodia-studio/kodia/internal/adapters/http/middleware"
	"github.com/kodia-studio/kodia/internal/core/domain"
	"github.com/kodia-studio/kodia/internal/core/ports"
	"github.com/kodia-studio/kodia/pkg/pagination"
)

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateUserInput) (*domain.User, error) {
	user := middleware.ForContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	result, err := r.UserService.Update(ctx, user.ID, ports.UpdateUserInput{
		Name:      input.Name,
		AvatarURL: input.AvatarURL,
	})
	return result, err
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	user := middleware.ForContext(ctx)
	if user == nil || user.Role != "admin" {
		return false, errors.New("unauthorized: admin role required")
	}

	err := r.UserService.Delete(ctx, id)
	return err == nil, err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain.User, error) {
	user := middleware.ForContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	return r.UserService.GetByID(ctx, user.ID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, page *int, perPage *int) (*model.PaginatedUsers, error) {
	user := middleware.ForContext(ctx)
	if user == nil || user.Role != "admin" {
		return nil, errors.New("unauthorized: admin role required")
	}

	p := 1
	pp := 15
	if page != nil {
		p = *page
	}
	if perPage != nil {
		pp = *perPage
	}

	users, total, err := r.UserService.GetAll(ctx, &pagination.Params{
		Page:    p,
		PerPage: pp,
	})
	if err != nil {
		return nil, err
	}

	return &model.PaginatedUsers{
		Users:   users,
		Total:   int(total),
		Page:    p,
		PerPage: pp,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*domain.User, error) {
	return r.UserService.GetByID(ctx, id)
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *domain.User) (string, error) {
	return string(obj.Role), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *domain.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *domain.User) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z"), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
